name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      DOTNET_ROLL_FORWARD: Major

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.201
    - name: Restore tools
      run: dotnet tool restore
    - name: Begin scan
      run: dotnet sonarscanner begin /o:"kaliumhexacyanoferrat" /k:"GenHTTP.Website" /d:sonar.login="$SONAR_TOKEN" /d:sonar.exclusions="**/bin/**/*,**/obj/**/*" /d:sonar.host.url="https://sonarcloud.io" 
    - name: Build project
      run: dotnet build GenHTTP.Website.sln -c Release
    - name: End scan
      run: dotnet sonarscanner end /d:sonar.login="$SONAR_TOKEN" /d:sonar.branch.name="${GITHUB_REF##*/}"
